### ISSUE TITLE
Caret (text cusor) is one character behind

### ISSUE THREAD

**Issue by creator2013** [WilliamVenner/SQLWorkbench#1]
When typing into the query field, the caret is one character behind. If you hit backspace it will delete the character behind the caret. This leads to a confusion when typing.
![Gif](https://i.gyazo.com/f35d6e31317544387e876e624308202c.gif)

And it seems that the auto complete is rarely working

**Comment by WilliamVenner** [comment]
This is a problem with the Ace code editor or Garry's Mod itself. Have you tried switching to the Chromium branch?
