### ISSUE TITLE
Errors after opening the menu

### ISSUE THREAD

**Issue by Nexeonenn** [WilliamVenner/SQLWorkbench#3]
Couldn't include file 'sqlworkbench\ace\ace.js.1.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 520))
Couldn't include file 'sqlworkbench\ace\ace.js.2.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 520))
Couldn't include file 'sqlworkbench\ace\ext-language_tools.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 521))
Couldn't include file 'sqlworkbench\ace\theme-monokai.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 522))
Couldn't include file 'sqlworkbench\ace\mode-mysql.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 523))
Couldn't include file 'sqlworkbench\ace\mode-sql.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 524))
Couldn't include file 'sqlworkbench\ace\snippets\mysql.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 525))
Couldn't include file 'sqlworkbench\ace\snippets\sql.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 526))
Couldn't include file 'sqlworkbench\ace\sql-formatter.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 527))

[ERROR] addons/sqlworkbench/lua/sqlworkbench/menu.lua:592: attempt to concatenate a nil value
  1. CreateConnection - addons/sqlworkbench/lua/sqlworkbench/menu.lua:592
   2. func - addons/sqlworkbench/lua/sqlworkbench/menu.lua:1113
    3. unknown - lua/includes/extensions/net.lua:32

Player [2][Nexeonenn] ERR: Couldn't include file 'sqlworkbench\ace\ace.js.1.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 520))
Player [2][Nexeonenn] ERR: Couldn't include file 'sqlworkbench\ace\ace.js.2.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 520))
Player [2][Nexeonenn] ERR: Couldn't include file 'sqlworkbench\ace\ext-language_tools.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 521))
Player [2][Nexeonenn] ERR: Couldn't include file 'sqlworkbench\ace\theme-monokai.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 522))
Player [2][Nexeonenn] ERR: Couldn't include file 'sqlworkbench\ace\mode-mysql.js.lua' (File not found) (@addons/sqlworkbench/lua/sqlworkbench/menu.lua (line 523))

**Comment by Nexeonenn** [comment]
SQLite is not working.
![image](https://user-images.githubusercontent.com/16958785/71615350-72187f00-2be3-11ea-9555-d1d46250d65d.png)
![image](https://user-images.githubusercontent.com/16958785/71615395-b99f0b00-2be3-11ea-913c-d25b1c3b23a6.png)

**Comment by WilliamVenner** [comment]
Can't reproduce this, it seems to work fine for me.

**Comment by theepicsaxguy** [comment]
Experiencing the same issue here.

**Comment by tominal** [comment]
Thought this would be cute to try but I got the same errors as everyone else. Something is wrong with the GetAceScript function's include which I didn't care much for. If you butcher the menu and remove all of the Ace.c9.io code it works just fine.

Cool script!

![](https://i.imgur.com/PdcM0Ol.png)

**Comment by WilliamVenner** [comment]
Just tested again, it appears to all be working fine for me :(

**Comment by tominal** [comment]
Are you putting it in addons or in the main directory? I could be fucking this up lol

**Comment by WilliamVenner** [comment]
addons

**Comment by SebastianL-NT** [comment]
![obraz](https://user-images.githubusercontent.com/22307314/86701808-a47fba80-c012-11ea-8428-3ca5eb9b2259.png)

Any idea? On client I have subscribed it from workshop and on server it is in addons folder.

**Comment by LokiPan** [comment]
Same issue here
@WilliamVenner can you give details of how your server is set up? 
Beta branch?
Windows or Linux, etc..?

**Comment by LokiPan** [comment]
> 
> 
> Thought this would be cute to try but I got the same errors as everyone else. Something is wrong with the GetAceScript function's include which I didn't care much for. If you butcher the menu and remove all of the Ace.c9.io code it works just fine.
> 
> Cool script!
> 
> ![](https://camo.githubusercontent.com/6e0fbd8e1edbe172263a29478d761ad98cdc7caa/68747470733a2f2f692e696d6775722e636f6d2f5064634d304f6c2e706e67)


I tried removing a bunch of the ace related stuff. Tried many times with various edits but cannot get it to work
Would you please post with which lines you removed?

**Comment by ceifa** [comment]
Same here. Server running on linux x64.
